name: universe
description: Social app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  fluttertoast: ^8.0.9
  http: ^0.13.4
  connectivity_plus: ^2.3.0
  flutter_bloc: ^8.0.1
  rxdart: ^0.27.3
  jiffy: ^5.0.0
  image_picker: ^0.8.5+3
  firebase_core: ^1.17.0
  firebase_storage: ^10.2.16
  cloud_firestore: ^3.1.15
  firebase_messaging: ^11.4.0
  firebase_auth: ^3.3.18
  awesome_dialog: ^2.2.1
  dropdown_search: ^4.0.1
  google_sign_in: ^5.3.1
  sqflite: ^2.0.2+1
  pull_to_refresh: ^2.0.0
  file_picker: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Almarai
      fonts:
        - asset: fonts/Almarai/Almarai-Regular.ttf
        - asset: fonts/Almarai/Almarai-Bold.ttf
        - asset: fonts/Almarai/Almarai-ExtraBold.ttf
        - asset: fonts/Almarai/Almarai-Light.ttf